name: Release

on:
  push:
    tags:
      - 'v*'

env:
  PACKAGE_NAME: fluvio-client-cpp-linux-x64

jobs:
  build_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DFLUVIO_CLIENT_CPP_BUILD_TESTS=OFF \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/${{ env.PACKAGE_NAME }}

      - name: Build CMake project
        run: cmake --build build --config Release --parallel

      - name: Install CMake project
        run: cmake --install build --config Release

      - name: Package Release Tarball
        run: tar -czvf ${{ env.PACKAGE_NAME }}.tar.gz ${{ env.PACKAGE_NAME }}/

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.PACKAGE_NAME }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
